### ISSUE TITLE
typoなど

### ISSUE THREAD

**Issue by Sorasky4** [t4t5u0/2020_fun_ai_docs#5]
第一回、環境構築のサークル資料
https://github.com/t4t5u0/2020_fun_ai_docs/blob/master/01_FUN_AI_Docs.ipynb
にて、typo?がいくつか見られたのであげておきます。
1. 見出しにある「Python(Anconda)の環境構築」
    Aconda -> Anaconda
2. VSCode のインストール 下のエクステンションで紹介している3番目
    Visual Studio Intelisince -> Visual Studio Intellisense
    ではないでしょうか。また、どちらもVSCode内で検索しても出てきません・・・。
3. 2と同じ見出しの最後のほう
    $ conda acivate circle -> $ conda activate circle
    だと思います。

**Comment by t4t5u0** [comment]
https://github.com/t4t5u0/2020_fun_ai_docs/commit/3b2edd297e1e5898283f9581c539cd0c8a73285c
このコミットにより修正。協力感謝！
